services:
    captain.cornfieldfoeposts.listener:
        class: captain\cornfieldfoeposts\event\listener
        arguments:
            - '@request'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@config'	
        tags:
            - { name: event.listener }